# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  
  TestFlight.takeOff('5ecab6ee35a10655399dfc815bd118a5_Mjk5MDk3MjAxMy0xMS0xMiAyMDowNTowOS44OTUwOTI')
  end)
end
